# CI de Nível 01 - Disparo manual a partir de 1 clique

name: 'Execução Manual'

on:
  workflow_dispatch:

jobs:
  e2e-tests:

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: cypress-io/github-action@v6
        with:
          browser: chrome
          headed: true

      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: relatorio-de-testes
          path: ./cypress/results
